interface ParitySuite {
  file: string;
  tests: string[];
}

const PARITY_SUITES: ParitySuite[] = [
  {
    file: "cache.test.ts",
    tests: [
      "stores and retrieves values",
      "returns null for missing keys",
      "has() returns true for existing keys",
      "delete() removes a key",
      "clear() removes all keys",
      "expires entries after TTL",
      "has() returns false after TTL expiry",
      "allows per-key TTL override",
      "stores complex objects",
      "constructor throws for NaN TTL",
      "constructor throws for negative TTL",
      "set() throws for NaN per-key TTL",
      "TTL of 0 expires immediately",
      "set() throws for negative per-key TTL",
      "set() throws for Infinity per-key TTL",
      "constructor with TTL of 0 expires entries immediately",
    ],
  },
  {
    file: "index-store.test.ts",
    tests: [
      "creates a combined index sheet",
      "adds and looks up entries",
      "enforces unique index",
      "allows same entity to re-index with same value (unique)",
      "removes entries when value is cleared in update",
      "removes all entries for an entity",
      "updates entries when value changes",
      "supports independent lookups per indexed field",
      "drops a combined index",
      "cancelIndexBatch() discards buffered entries",
      "removeMultipleFromCombined() bulk-removes entries",
      "removeMultipleFromCombined() no-op for empty array",
      "existsCombined() checks for index sheet",
      "getIndexedFields() returns registered fields",
      "searchCombined (n-gram) > finds exact token match",
      "searchCombined (n-gram) > finds partial match via trigrams",
      "searchCombined (n-gram) > is case insensitive",
      "searchCombined (n-gram) > handles multi-token query (intersection)",
      "searchCombined (n-gram) > returns empty for no match",
      "searchCombined (n-gram) > respects limit parameter",
      "searchCombined (n-gram) > finds match through normalized separators",
      "searchCombined (n-gram) > invalidates search cache after flushIndexBatch",
      "searchCombined (n-gram) > invalidates search index cache on data change",
      "searchCombined (n-gram) > returns empty for empty query",
      "searchCombined (n-gram) > finds substring within a token via trigrams",
      "normalizeForSearch > lowercases and trims",
      "normalizeForSearch > normalizes dashes to spaces",
      "normalizeForSearch > collapses whitespace",
      "normalizeForSearch > returns empty for null-ish input",
      "ngrams > generates trigrams",
      "ngrams > returns empty for short input",
      "ngrams > strips whitespace before generating",
      "searchCombined (n-gram) > returns empty array for limit=0",
      "searchCombined (n-gram) > finds match for query shorter than trigram size",
      "lookupCombined returns empty for non-existent index table",
      "updateInCombined throws unique violation when value conflicts with another entity",
      "addAllFieldsToCombined detects unique violation in pending batch entries",
      "operates correctly without cache provider",
      "removeMultipleFromCombined is no-op for non-existent entity IDs",
      "updateInCombined creates entry when field goes from empty to populated",
      "normalizeForSearch > normalizes em-dashes and underscores to spaces",
      "lookupCombined deduplicates entityIds when same entity indexed twice",
      "searchCombined deduplicates entityIds from repeated index entries",
      "clearAllCaches() allows the search cache to be rebuilt",
    ],
  },
  {
    file: "query.test.ts",
    tests: [
      "filters with where()",
      "chains multiple where() as AND",
      "sorts results",
      "limits results",
      "applies offset",
      "limit() throws for negative number",
      "limit() throws for NaN",
      "offset() throws for negative number",
      "offset() throws for Infinity",
      "first() returns the first match",
      "first() returns null when no match",
      "first() respects offset",
      "count() returns matching count",
      "select() returns paginated result",
      "select() applies orderBy before pagination",
      "groupBy() groups results",
      "build() returns query options",
      "build() includes offset when set alone",
      "returns entities matching either condition",
      "applies AND within each OR group",
      "chains multiple or() calls",
      "works with orderBy",
      "works with limit and offset",
      "first() returns first OR match",
      "count() counts OR matches",
      "select() paginates OR results",
      "groupBy() groups OR results",
      "build() returns whereGroups for OR queries",
      "build() returns where (not whereGroups) for AND-only queries",
      "or() without preceding where() still filters correctly",
      "or().and() without preceding where() chains correctly",
      "execute() with limit(0) returns an empty array",
      "first() with limit(0) returns null",
      "build() with limit(0) includes limit 0",
      "build() with no filters returns all undefined options",
      "first() returns null when offset exceeds result count",
      "groupBy() respects orderBy before grouping",
      "execute() with orderBy and offset combined returns correct slice",
      "execute() returns items from offset when no limit is set",
      "limit() and offset() floor fractional values",
      "Query.from() without resolver throws descriptive error",
    ],
  },
  {
    file: "query-engine.test.ts",
    tests: [
      "filters with = operator",
      "filters with != operator",
      "filters with > operator",
      "filters with < operator",
      "filters with >= and <= operators",
      "filters with contains operator",
      "contains is case-insensitive for uppercase query",
      "filters with startsWith operator",
      "filters with in operator",
      "filters with search operator (substring match)",
      "applies multiple filters as AND",
      "returns all when no filters",
      "sorts ascending by number",
      "returns original array reference when no sort clauses",
      "sorts descending by number",
      "sorts by string",
      "sorts by multiple fields",
      "does not mutate original array",
      "returns first page",
      "returns last page",
      "returns empty if offset exceeds total",
      "groups by field",
      "groups by boolean",
      "combines filter + sort + pagination",
      "applies only sort and limit when no filters are provided",
      "returns all entities for empty options",
      "matches entities passing any group",
      "applies AND within each group",
      "returns all entities for empty groups",
      "empty group within OR groups matches nothing",
      "uses OR groups when whereGroups is provided",
      "prefers whereGroups over where",
      "contains with non-string value matches nothing",
      "startsWith with non-string value matches nothing",
      "search with non-string value matches nothing",
      "negative offset is clamped to 0",
      "negative limit defaults to full length",
      "NaN offset defaults to 0",
      "returns no matches for an unrecognized operator",
      "returns false when field type differs from value type (number vs string)",
      "compares strings when both field and value are strings",
      "filters by nested dot-path field",
      "filters by nested slash-path field",
      "sorts by nested field",
      "returns undefined for missing nested segment",
      "uses Set for arrays with more than 8 elements",
      "returns empty items when limit is 0",
      "places null values before non-null in ascending order",
      "places null values last in descending sort",
      "groups entities including those with undefined keys",
      "sortEntities returns empty array for empty input",
      "groupEntities returns empty array for empty input",
      "filterEntities with empty entity list returns empty",
      "paginateEntities with Infinity limit defaults to full length",
      "sortEntities treats both-null values as equal",
      "in operator with non-array value returns empty result",
      "in operator with >8 elements uses Set-based path",
      "contains operator with non-string entity value returns false",
      "executeQuery applies offset without limit correctly",
      "normalizes non-finite offset and limit in executeQuery",
    ],
  },
  {
    file: "serialization.test.ts",
    tests: [
      "serializes string",
      "serializes number",
      "serializes boolean",
      "serializes json",
      "serializes date",
      "serializes date type with non-Date string value",
      "serializes reference",
      "deserializes string",
      "applies defaultValue when empty",
      "deserializes number",
      "deserializes boolean",
      "deserializes date from ISO string",
      "deserializes reference type as string",
      "deserializes json",
      "deserializes json type with non-string value returns it as-is",
      "prepends system columns",
      "round-trips an entity",
      "round-trips an entity with explicit fieldMap",
      "handles missing optional fields",
      "round-trips json string values",
      "deserializes native Date objects in date fields to ISO strings",
      "deserializes date from numeric cell value as string",
      "serializes Infinity as empty for number type",
      "serializes Infinity string as empty for number type",
      "serializes invalid Date as empty for date type",
      "auto-infers number type when fieldDef.type is undefined",
      "auto-infers boolean type when fieldDef.type is undefined",
      "auto-infers object as JSON when fieldDef.type is undefined",
      "auto-infers valid Date to ISO string when fieldDef.type is undefined",
      "auto-infers string type as String() when fieldDef.type is undefined",
      "deserializes Infinity as null for number type",
      "deserializes Infinity string as null for number type",
      "deserializes invalid Date object as null for date type",
      "returns raw value when fieldDef.type is undefined",
      "auto-infers invalid Date as empty string when fieldDef.type is undefined",
      "serializes NaN as empty for number type",
      "deserializes boolean from number 0 and 1",
      "deserializes boolean string false as false",
      "deserializes yes as true and numeric-string zero as false for boolean type",
      "deserializes boolean string one as true",
      "serializes boolean from string yes/no",
      "serializes unrecognized field type as string",
      "deserializes unrecognized field type as raw value",
      "rowToEntity handles row shorter than headers",
      "entityToRow uses raw value for column without field definition",
      "rowToEntity keeps raw value for column without field definition",
      "rowToEntity converts Date objects in system columns to ISO strings",
    ],
  },
  {
    file: "uuid.test.ts",
    tests: [
      "returns a string of UUID v4 format",
      "generates unique values",
      "falls back to Math.random when crypto is unavailable",
      "uses GAS Utilities.getUuid when available",
      "uses crypto.getRandomValues when available",
    ],
  },
  {
    file: "record.test.ts",
    tests: [
      "creates a new entity with auto-generated ID",
      "auto-creates the table on first save",
      "updates an existing entity",
      "returns this for chaining",
      "persists update via findById round-trip",
      "throws on missing required field",
      "sets a field value and returns this",
      "supports chaining set calls",
      "get() retrieves a field value",
      "deletes a saved entity",
      "returns false for unsaved entity",
      "returns a plain object with all fields",
      "creates instance with data via static create()",
      "finds a saved entity by ID",
      "returns null for non-existent ID",
      "returns all entities",
      "returns entities matching query",
      "returns first matching entity",
      "returns null when no match",
      "returns a Query and chains",
      "returns a Query",
      "counts all entities",
      "counts with filter",
      "deletes matching entities",
      "returns paginated results",
      "groups entities by field",
      "creates separate tables for each class",
      "works with class reference (typed)",
      "works with string name",
      "works with table name string",
      "supports full fluent chain",
      "throws for unknown class name",
      "create → query → update → delete cycle",
      "works with Query.from() end-to-end",
      "count() with whereGroups counts only matching entities",
      "deleteAll() with whereGroups deletes only matching entities",
      "select() with whereGroups paginates only matching entities",
      "groupBy() with whereGroups groups only matching entities",
      "invalidates cache when saveAll() fails mid-operation",
      "does not persist earlier updates when a later saveAll entry fails",
      "invalidates cache and re-throws on mid-batch failure",
      "batch is no longer active after commitBatch error",
      "clears class maps on re-configure",
      "clears entity cache and allows re-read from sheet",
      "falls back to sheet scan when cache entry is null",
      "skips rows with empty __id",
      "persists both new and updated entities in a single batch",
      "returns an entity when called with no filter",
      "deletes all entities and returns the count",
      "does not overwrite an existing entity when a gap row is present",
      "findById returns correct entity after gap row",
      "assigns correct row indices so delete targets the right entity",
      "discards buffered operations without writing",
      "beginBatch \u2192 save \u2192 delete \u2192 commitBatch applies all operations",
      "count() during batch returns sheet state, not buffered state",
      "returns correct entity without re-reading sheet data",
      "delete() returns false on unsaved record (no __id)",
      "toJSON() returns undefined __id for unsaved entity",
      "saveAll() with empty array returns empty array",
      "deleteAll() returns zero when no entities match filter",
      "save() includes null fields but excludes undefined fields",
      "Query.from(Class) auto-registers class without prior save",
      "deleteAll uses individual deletes for 2 entities and bulk for 3",
      "bulk deleteAll removes gap rows from sheet as expected",
      "indexed search with additional where filter narrows results",
      "Field defaultValue fills missing property on save",
      "Field() without options still registers and persists the field",
      "Field type date stores Date as ISO string in sheet round-trip",
      "resetDecoratorCaches() keeps @Field metadata effective",
      "Field({ required: true }) enforces required validation",
      "returns the shared IndexStore instance",
      "batch save updates existing entity when committed",
      "throws when indexed model has no indexTableName",
      "getClassByName resolves class by table name fallback",
    ],
  },
  {
    file: "sheet-repository.test.ts",
    tests: [
      "onValidate rejects save when validation errors returned",
      "beforeSave mutates entity payload",
      "afterSave receives saved entity and isNew flag",
      "beforeDelete returning false blocks deletion",
      "beforeDelete veto on deleteAll returns zero and preserves data",
      "beforeDelete veto on deleteAll can preserve selected entities",
      "beforeDelete partial veto works for deleteAll small-batch path",
      "afterDelete is called with deleted entity ID",
      "afterDelete is called for each entity removed by deleteAll",
      "afterDelete is called for each entity removed by deleteAll small-batch path",
      "getSheet throws when sheet does not exist",
      "loadAllEntities throws during active saveAll entity batch",
      "findById returns a detached copy from cache",
      "query() returns detached copies from cache-backed reads",
      "save() in batch mode with explicit __id sets __createdAt for new entity",
      "commitBatch persists queued save with explicit __id for new entity",
      "two queued saves with same explicit __id produce one updated entity after commit",
      "two queued saves with same explicit __id trigger afterSave as create then update",
      "commitBatch() is a no-op when no batch is active",
      "rollbackBatch() is a no-op when no batch is active",
      "rollbackBatch discards queued operations and does not trigger save/delete hooks",
      "beginBatch() resets the buffer when batch is already active",
      "queued save applies beforeSave and triggers afterSave on commit",
      "queued update applies beforeSave and triggers afterSave with isNew=false",
      "queued update by __id without __createdAt updates existing entity and preserves createdAt",
      "deleteAll() in batch mode queues deletes for deferred execution",
      "deleteAll(options) in batch mode queues only matching deletes",
      "delete() in batch mode with non-existent ID is a deferred no-op after commit",
      "afterDelete is called for queued delete when batch is committed",
      "afterDelete is not called for missing queued delete on commit",
      "missing delete in batch does not block valid queued operations",
      "delete() outside batch returns false for non-existent ID",
      "delete() falls back to full scan when cached row index is stale",
      "deleteAll(options) in batch mode returns zero when nothing matches",
      "beforeDelete veto is respected when queued deleteAll is committed",
    ],
  },
];

function toParityCaseId(file: string, testName: string): string {
  return `${file}::${testName}`;
}

const PARITY_CASE_IDS: string[] = PARITY_SUITES.flatMap((suite) =>
  suite.tests.map((testName) => toParityCaseId(suite.file, testName)),
);

export class ParityCatalog {
  static readonly SUITES = PARITY_SUITES;
  static readonly CASE_IDS = PARITY_CASE_IDS;
  static toCaseId = toParityCaseId;
}
