export interface ParitySuite {
  file: string;
  tests: string[];
}

export const PARITY_SUITES: ParitySuite[] = [
  {
    file: "cache.test.ts",
    tests: [
      "stores and retrieves values",
      "returns null for missing keys",
      "has() returns true for existing keys",
      "delete() removes a key",
      "clear() removes all keys",
      "expires entries after TTL",
      "allows per-key TTL override",
      "stores complex objects",
    ],
  },
  {
    file: "index-store.test.ts",
    tests: [
      "creates an index sheet",
      "adds and looks up entries",
      "enforces unique index",
      "allows same entity to re-index with same value (unique)",
      "removes entries",
      "removes all entries for an entity",
      "updates entries when value changes",
      "rebuilds index from entity data",
      "drops an index",
      "exists() checks for index sheet",
      "getIndexedFields() returns registered fields",
    ],
  },
  {
    file: "query-builder.test.ts",
    tests: [
      "filters with where()",
      "chains multiple where() as AND",
      "sorts results",
      "limits results",
      "applies offset",
      "first() returns the first match",
      "first() returns null when no match",
      "count() returns matching count",
      "select() returns paginated result",
      "groupBy() groups results",
      "build() returns query options",
    ],
  },
  {
    file: "query-engine.test.ts",
    tests: [
      "filters with = operator",
      "filters with != operator",
      "filters with > operator",
      "filters with < operator",
      "filters with >= and <= operators",
      "filters with contains operator",
      "filters with startsWith operator",
      "filters with in operator",
      "applies multiple filters as AND",
      "returns all when no filters",
      "sorts ascending by number",
      "sorts descending by number",
      "sorts by string",
      "sorts by multiple fields",
      "does not mutate original array",
      "returns first page",
      "returns last page",
      "returns empty if offset exceeds total",
      "groups by field",
      "groups by boolean",
      "combines filter + sort + pagination",
    ],
  },
  {
    file: "repository.test.ts",
    tests: [
      "creates a new entity with auto-generated ID",
      "retrieves by ID",
      "updates an existing entity",
      "throws on missing required field",
      "finds all entities",
      "find with filter",
      "findOne returns first match",
      "findOne returns null when no match",
      "deletes by ID",
      "returns false for non-existent ID",
      "deleteAll removes matching entities",
      "counts all entities",
      "counts with filter",
      "select returns paginated result",
      "returns a QueryBuilder that works",
      "groups entities by field",
      "calls beforeSave and afterSave",
      "calls onValidate and rejects on errors",
      "calls beforeDelete and can cancel",
      "buffers and commits",
      "rollback discards buffered operations",
    ],
  },
  {
    file: "schema-migrator.test.ts",
    tests: [
      "initializes meta sheet and data sheet",
      "sets headers on data sheet",
      "creates indexes during initialization",
      "stores schema in _meta sheet",
      "tableExists returns correct value",
      "addField adds a column to the schema",
      "addField is idempotent for existing fields",
      "addField throws for unknown table",
      "removeField removes a field from schema",
      "sync initializes if table does not exist",
      "sync adds missing fields to existing table",
      "sync adds missing indexes",
    ],
  },
  {
    file: "serialization.test.ts",
    tests: [
      "serializes string",
      "serializes number",
      "serializes boolean",
      "serializes json",
      "serializes date",
      "serializes reference",
      "deserializes string",
      "applies defaultValue when empty",
      "deserializes number",
      "deserializes boolean",
      "deserializes json",
      "prepends system columns",
      "round-trips an entity",
      "handles missing optional fields",
    ],
  },
  {
    file: "sheetorm.test.ts",
    tests: [
      "registers a schema and creates sheets",
      "getRepository returns a working repo",
      "getRepository caches instances",
      "throws when getting repo for unregistered table",
      "static create() works",
      "clearCache() clears the cache",
      "getMigrator() returns the migrator",
      "getIndexStore() returns the index store",
      "full workflow: register → save → query → delete",
    ],
  },
  {
    file: "uuid.test.ts",
    tests: ["returns a string of UUID v4 format", "generates unique values"],
  },
  {
    file: "record.test.ts",
    tests: [
      "creates a new entity with auto-generated ID",
      "auto-creates the table on first save",
      "updates an existing entity",
      "returns this for chaining",
      "persists update via findById round-trip",
      "throws on missing required field",
      "sets a field value and returns this",
      "supports chaining set calls",
      "get() retrieves a field value",
      "deletes a saved entity",
      "returns false for unsaved entity",
      "returns a plain object with all fields",
      "initializes fields from data object",
      "finds a saved entity by ID",
      "returns null for non-existent ID",
      "returns all entities",
      "returns entities matching query",
      "returns first matching entity",
      "returns null when no match",
      "returns a QueryBuilder and chains",
      "returns a QueryBuilder",
      "counts all entities",
      "counts with filter",
      "deletes matching entities",
      "returns paginated results",
      "groups entities by field",
      "creates separate tables for each class",
      "works with class reference (typed)",
      "works with string name",
      "works with table name string",
      "supports full fluent chain",
      "throws for unknown class name",
      "create → query → update → delete cycle",
      "works with QueryBuilder.from() end-to-end",
    ],
  },
];

export function toParityCaseId(file: string, testName: string): string {
  return `${file}::${testName}`;
}

export const PARITY_CASE_IDS: string[] = PARITY_SUITES.flatMap((suite) =>
  suite.tests.map((testName) => toParityCaseId(suite.file, testName)),
);
