interface ParitySuite {
  file: string;
  tests: string[];
}

const PARITY_SUITES: ParitySuite[] = [
  {
    file: "cache.test.ts",
    tests: [
      "stores and retrieves values",
      "returns null for missing keys",
      "has() returns true for existing keys",
      "delete() removes a key",
      "clear() removes all keys",
      "expires entries after TTL",
      "allows per-key TTL override",
      "stores complex objects",
    ],
  },
  {
    file: "index-store.test.ts",
    tests: [
      "creates a combined index sheet",
      "adds and looks up entries",
      "enforces unique index",
      "allows same entity to re-index with same value (unique)",
      "removes entries when value is cleared in update",
      "removes all entries for an entity",
      "updates entries when value changes",
      "supports independent lookups per indexed field",
      "drops a combined index",
      "existsCombined() checks for index sheet",
      "getIndexedFields() returns registered fields",
      "searchCombined (n-gram) > finds exact token match",
      "searchCombined (n-gram) > finds partial match via trigrams",
      "searchCombined (n-gram) > is case insensitive",
      "searchCombined (n-gram) > handles multi-token query (intersection)",
      "searchCombined (n-gram) > returns empty for no match",
      "searchCombined (n-gram) > respects limit parameter",
      "searchCombined (n-gram) > finds match through normalized separators",
      "searchCombined (n-gram) > invalidates search index cache on data change",
      "searchCombined (n-gram) > returns empty for empty query",
      "searchCombined (n-gram) > finds substring within a token via trigrams",
      "normalizeForSearch > lowercases and trims",
      "normalizeForSearch > normalizes dashes to spaces",
      "normalizeForSearch > collapses whitespace",
      "normalizeForSearch > returns empty for null-ish input",
      "ngrams > generates trigrams",
      "ngrams > returns empty for short input",
      "ngrams > strips whitespace before generating",
    ],
  },
  {
    file: "query.test.ts",
    tests: [
      "filters with where()",
      "chains multiple where() as AND",
      "sorts results",
      "limits results",
      "applies offset",
      "first() returns the first match",
      "first() returns null when no match",
      "count() returns matching count",
      "select() returns paginated result",
      "groupBy() groups results",
      "build() returns query options",
      "returns entities matching either condition",
      "applies AND within each OR group",
      "chains multiple or() calls",
      "works with orderBy",
      "works with limit and offset",
      "first() returns first OR match",
      "count() counts OR matches",
      "select() paginates OR results",
      "groupBy() groups OR results",
      "build() returns whereGroups for OR queries",
      "build() returns where (not whereGroups) for AND-only queries",
    ],
  },
  {
    file: "query-engine.test.ts",
    tests: [
      "filters with = operator",
      "filters with != operator",
      "filters with > operator",
      "filters with < operator",
      "filters with >= and <= operators",
      "filters with contains operator",
      "filters with startsWith operator",
      "filters with in operator",
      "filters with search operator (substring match)",
      "applies multiple filters as AND",
      "returns all when no filters",
      "sorts ascending by number",
      "sorts descending by number",
      "sorts by string",
      "sorts by multiple fields",
      "does not mutate original array",
      "returns first page",
      "returns last page",
      "returns empty if offset exceeds total",
      "groups by field",
      "groups by boolean",
      "combines filter + sort + pagination",
      "matches entities passing any group",
      "applies AND within each group",
      "returns all entities for empty groups",
      "uses OR groups when whereGroups is provided",
      "prefers whereGroups over where",
    ],
  },
  {
    file: "serialization.test.ts",
    tests: [
      "serializes string",
      "serializes number",
      "serializes boolean",
      "serializes json",
      "serializes date",
      "serializes reference",
      "deserializes string",
      "applies defaultValue when empty",
      "deserializes number",
      "deserializes boolean",
      "deserializes json",
      "prepends system columns",
      "round-trips an entity",
      "handles missing optional fields",
    ],
  },
  {
    file: "uuid.test.ts",
    tests: ["returns a string of UUID v4 format", "generates unique values"],
  },
  {
    file: "record.test.ts",
    tests: [
      "creates a new entity with auto-generated ID",
      "auto-creates the table on first save",
      "updates an existing entity",
      "returns this for chaining",
      "persists update via findById round-trip",
      "throws on missing required field",
      "sets a field value and returns this",
      "supports chaining set calls",
      "get() retrieves a field value",
      "deletes a saved entity",
      "returns false for unsaved entity",
      "returns a plain object with all fields",
      "creates instance with data via static create()",
      "finds a saved entity by ID",
      "returns null for non-existent ID",
      "returns all entities",
      "returns entities matching query",
      "returns first matching entity",
      "returns null when no match",
      "returns a Query and chains",
      "returns a Query",
      "counts all entities",
      "counts with filter",
      "deletes matching entities",
      "returns paginated results",
      "groups entities by field",
      "creates separate tables for each class",
      "works with class reference (typed)",
      "works with string name",
      "works with table name string",
      "supports full fluent chain",
      "throws for unknown class name",
      "create → query → update → delete cycle",
      "works with Query.from() end-to-end",
      "count() with whereGroups counts only matching entities",
      "deleteAll() with whereGroups deletes only matching entities",
      "select() with whereGroups paginates only matching entities",
      "groupBy() with whereGroups groups only matching entities",
    ],
  },
];

function toParityCaseId(file: string, testName: string): string {
  return `${file}::${testName}`;
}

const PARITY_CASE_IDS: string[] = PARITY_SUITES.flatMap((suite) =>
  suite.tests.map((testName) => toParityCaseId(suite.file, testName)),
);

export class ParityCatalog {
  static readonly SUITES = PARITY_SUITES;
  static readonly CASE_IDS = PARITY_CASE_IDS;
  static toCaseId = toParityCaseId;
}
